{{ range .Values.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-token
  namespace: {{ $.Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .name }}
type: kubernetes.io/service-account-token
{{ end }}