namespace: my-namespace
team: my-team

ResourceQuota:
  requests:
    cpu: "1"
    memory: "2Gi"
    storage: "10Gi"
  limits:
    cpu: "2"
    memory: "4Gi"
  pods: "20"

repository:
  kind: GitRepository
  url: https://github.com/my-org/my-repo
  branch: main
  interval: 10m
  path: ./
  secretRef:
    name: ""

extraSubjects: []
# example:
# extraSubjects:
#   - my-team

networkPolicy:
  endpointSelector: {}
  ingress: []
  egress: []
  # ingress:
  #   - fromNamespace:
  #       k8s:io.kubernetes.pod.namespace: gateway-system
  #   - fromNamespace:
  #       k8s:io.kubernetes.pod.namespace: monitoring
  # egress:
  #   - toNamespace:
  #       k8s:io.kubernetes.pod.namespace: database
